# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt install -y python-pip
    sudo pip install numpy
    python tests.py
  workingDirectory: string-calculator/python
  displayName: 'Run String-Calculator Python Tests'
